const tracklist = [
  // Heros
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/01 - Beauty and the Beast (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/02 - Joe the Lion (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/03 - _Heroes_ (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/04 - Sons of the Silent Age (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/05 - Blackout (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/06 - V-2 Schneider (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/07 - Sense of Doubt (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/08 - Moss Garden (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/09 - Neuköln (2017 Remastered Version).mp3",
  "../tracks/David Bowie/Heroes (2017 Remastered Version)/10 - The Secret Life of Arabia (2017 Remastered Version).mp3",
  // American Dream
  "../tracks/LCD Soundsystem/american dream/01 - oh baby.mp3",
  "../tracks/LCD Soundsystem/american dream/02 - other voices.mp3",
  "../tracks/LCD Soundsystem/american dream/03 - i used to.mp3",
  "../tracks/LCD Soundsystem/american dream/04 - change yr mind.mp3",
  "../tracks/LCD Soundsystem/american dream/05 - how do you sleep_.mp3",
  "../tracks/LCD Soundsystem/american dream/06 - tonite.mp3",
  "../tracks/LCD Soundsystem/american dream/07 - call the police.mp3",
  "../tracks/LCD Soundsystem/american dream/08 - american dream.mp3",
  "../tracks/LCD Soundsystem/american dream/09 - emotional haircut.mp3",
  "../tracks/LCD Soundsystem/american dream/10 - black screen.mp3",
  // Currents
  "../tracks/Tame Impala/Currents [Explicit]/01 - Let It Happen.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/02 - Nangs.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/03 - The Moment.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/04 - Yes I'm Changing [Explicit].mp3",
  "../tracks/Tame Impala/Currents [Explicit]/05 - Eventually.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/06 - Gossip.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/07 - The Less I Know The Better [Explicit].mp3",
  "../tracks/Tame Impala/Currents [Explicit]/08 - Past Life.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/09 - Disciples.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/10 - 'Cause I'm A Man [Explicit].mp3",
  "../tracks/Tame Impala/Currents [Explicit]/11 - Reality In Motion.mp3",
  "../tracks/Tame Impala/Currents [Explicit]/12 - Love_Paranoia [Explicit].mp3",
  "../tracks/Tame Impala/Currents [Explicit]/13 - New Person, Same Old Mistakes.mp3",
  // The Eraser
  "../tracks/Thom Yorke/The Eraser/01 - The Eraser.mp3",
  "../tracks/Thom Yorke/The Eraser/02 - Analyse.mp3",
  "../tracks/Thom Yorke/The Eraser/03 - The Clock.mp3",
  "../tracks/Thom Yorke/The Eraser/04 - Black Swan.mp3",
  "../tracks/Thom Yorke/The Eraser/05 - Skip Divided.mp3",
  "../tracks/Thom Yorke/The Eraser/06 - Atoms For Peace.mp3",
  "../tracks/Thom Yorke/The Eraser/07 - And It Rained All Night.mp3",
  "../tracks/Thom Yorke/The Eraser/08 - Harrowdown Hill.mp3",
  "../tracks/Thom Yorke/The Eraser/09 - Cymbal Rush.mp3",
];

export default tracklist;